import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TimeKube: Kubernetes Snapshot Backup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // useEffect(()=> {
  //       // Load AWS SDK configuration
  //       config.update({
  //         accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  //         secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  //         region: process.env.NEXT_PUBLIC_AWS_REGION,
  //       });
  // },[]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>Test Navbar</nav>
        {children}
      </body>
    </html>
  );
}
